default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: postgres
  username: postgres
  password: password
  host: localhost

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  host: db.data
